#!/bin/sh
cd /home/jetpackpony/projects/softek
tmux has-session -t softek
if [ $? != 0 ]; then
  tmux new-session -s softek -n vim -d
  tmux send-keys -t softek 'vim' Enter
  tmux split-window -h -t softek
fi
tmux attach -t softek
